In [1]:
from textworld.gym import register_game
from textworld import EnvInfos
from textworld.text_utils import extract_vocab_from_gamefile
from textworld.gym.spaces.text_spaces import Word
import gym
from preproc import *

In [11]:
vocab = extract_vocab_from_gamefile('game/simple1.z8')
observation_space = Word(max_length=len(vocab), vocab=vocab)
action_space = Word(max_length=8, vocab=vocab)
request_infos = EnvInfos(inventory=True, intermediate_reward=True, admissible_commands=True, description=True)
env_id = register_game('game/simple1.z8', request_infos=request_infos, observation_space=observation_space, action_space=action_space)
env = gym.make(env_id)
state = env.reset()
print(state)

("\n\n\n\n                    ________  ________  __    __  ________        \n                   |        \\|        \\|  \\  |  \\|        \\       \n                    \\$$$$$$$$| $$$$$$$$| $$  | $$ \\$$$$$$$$       \n                      | $$   | $$__     \\$$\\/  $$   | $$          \n                      | $$   | $$  \\     >$$  $$    | $$          \n                      | $$   | $$$$$    /  $$$$\\    | $$          \n                      | $$   | $$_____ |  $$ \\$$\\   | $$          \n                      | $$   | $$     \\| $$  | $$   | $$          \n                       \\$$    \\$$$$$$$$ \\$$   \\$$    \\$$          \n              __       __   ______   _______   __        _______  \n             |  \\  _  |  \\ /      \\ |       \\ |  \\      |       \\ \n             | $$ / \\ | $$|  $$$$$$\\| $$$$$$$\\| $$      | $$$$$$$\\\n             | $$/  $\\| $$| $$  | $$| $$__| $$| $$      | $$  | $$\n             | $$  $$$\\ $$| $$  | $$| $$    $$| $$      | $$  | $$\n       

AttributeError: 'TextworldGymEnv' object has no attribute 'num_fields'

In [3]:
pre_env = TextWorldPreproc(env)
print(pre_env.reset())

{'obs': [array([  3, 263, 125, 313, 292, 215, 346, 239, 207, 144, 455, 111,   1,
       386, 314, 382, 239, 263, 125,   2,   3, 455, 396,  96, 214, 280,
        82,   2,   3, 455, 396, 372, 342, 239,  48, 338, 444,  31, 349,
        24,   2,   3, 455, 396, 372, 342, 239, 326,   2,   3, 206, 427,
       326, 240, 424, 283, 326, 416,  75, 316, 345,   2,   3, 276, 212,
       424,  93, 144, 427,  50,   2,   3,   1, 270, 345, 212,  25,   2,
         3, 455,   1, 240,  83,  67, 320, 437, 199,  42, 129, 179, 212,
       124,   2,   3,   2]), array([  3, 455,  78,   1, 239, 171, 406, 398, 239,  32, 253, 239, 304,
         2,   3,   2])], 'admissible_commands': [array([  3, 303, 304,   2]), array([  3, 303,  32,   2]), array([  3, 303, 171, 406, 398,   2]), array([  3, 453,  31,   2]), array([  3, 453, 326,   2]), array([  3, 453, 304,   2]), array([  3, 453,  32,   2]), array([  3, 453, 171, 406, 398,   2]), array([ 3, 59, 50,  2]), array([ 3, 59, 42,  2]), array([  3, 225,   2]), array([  3,

In [4]:
pre_env.step(0)

({'obs': [array([  3, 263, 125, 313, 292, 215, 346, 239, 207, 144, 455, 111,   1,
          386, 314, 382, 239, 263, 125,   2,   3, 455, 396,  96, 214, 280,
           82,   2,   3, 455, 396, 372, 342, 239,  48, 338, 444,  31, 349,
           24,   2,   3, 455, 396, 372, 342, 239, 326,   2,   3, 206, 427,
          326, 240, 424, 283, 326, 416,  75, 316, 345,   2,   3, 276, 212,
          424,  93, 144, 427,  50,   2,   3,   1, 270, 345, 212,  25,   2,
            3, 455,   1, 240,  83,  67, 320, 437, 199,  42, 129, 179, 212,
          124,   2,   3, 276, 212, 239, 304, 316, 427,   1,   2,   3,   2]),
   array([  3, 455,  78,   1, 239, 171, 406, 398, 253, 239,  32,   2,   3,
            2])],
  'admissible_commands': [array([  3, 303,  32,   2]),
   array([  3, 303, 171, 406, 398,   2]),
   array([  3, 453,  31,   2]),
   array([  3, 453, 326,   2]),
   array([  3, 453, 304,   2]),
   array([  3, 453,  32,   2]),
   array([  3, 453, 171, 406, 398,   2]),
   array([ 3, 59, 50,  2]),
   

In [5]:
pre_env.last_extra_info['inventory']

'You are carrying: a type D latchkey and a teacup.'

In [6]:
prep = Preprocessor(dict_size=pre_env.observation_space.vocab_size, emb_size=10, num_sequences=pre_env.num_fields, enc_output_size=20)

In [7]:
obs = pre_env.reset()
obs

{'obs': [array([  3, 263, 125, 313, 292, 215, 346, 239, 207, 144, 455, 111,   1,
         386, 314, 382, 239, 263, 125,   2,   3, 455, 396,  96, 214, 280,
          82,   2,   3, 455, 396, 372, 342, 239,  48, 338, 444,  31, 349,
          24,   2,   3, 455, 396, 372, 342, 239, 326,   2,   3, 206, 427,
         326, 240, 424, 283, 326, 416,  75, 316, 345,   2,   3, 276, 212,
         424,  93, 144, 427,  50,   2,   3,   1, 270, 345, 212,  25,   2,
           3, 455,   1, 240,  83,  67, 320, 437, 199,  42, 129, 179, 212,
         124,   2,   3,   2]),
  array([  3, 455,  78,   1, 239, 171, 406, 398, 239,  32, 253, 239, 304,
           2,   3,   2])],
 'admissible_commands': [array([  3, 303, 304,   2]),
  array([  3, 303,  32,   2]),
  array([  3, 303, 171, 406, 398,   2]),
  array([  3, 453,  31,   2]),
  array([  3, 453, 326,   2]),
  array([  3, 453, 304,   2]),
  array([  3, 453,  32,   2]),
  array([  3, 453, 171, 406, 398,   2]),
  array([ 3, 59, 50,  2]),
  array([ 3, 59, 42,  2])

In [8]:
prep

Preprocessor(
  (emb): Embedding(462, 10)
  (enc_0): Encoder(
    (net): LSTM(10, 20, batch_first=True)
  )
  (enc_1): Encoder(
    (net): LSTM(10, 20, batch_first=True)
  )
  (enc_commands): Encoder(
    (net): LSTM(10, 20, batch_first=True)
  )
)

In [9]:
prep.encode_sequences([obs['obs']]).size()

[torch.Size([95, 10])]
[torch.Size([16, 10])]


torch.Size([1, 40])

In [10]:
prep.encode_commands(obs['admissible_commands']).size()

[torch.Size([4, 10]), torch.Size([4, 10]), torch.Size([6, 10]), torch.Size([4, 10]), torch.Size([4, 10]), torch.Size([4, 10]), torch.Size([4, 10]), torch.Size([6, 10]), torch.Size([4, 10]), torch.Size([4, 10]), torch.Size([3, 10]), torch.Size([3, 10]), torch.Size([4, 10]), torch.Size([6, 10]), torch.Size([6, 10]), torch.Size([8, 10])]


torch.Size([16, 20])